In [13]:
class Employee:
    employee_count = 0

    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.employee_count += 1

    def average_salary(self, total_salary):
        return total_salary / Employee.employee_count

class FulltimeEmployee(Employee):
    pass

employee1 = Employee("Nitish Harsha", "Somarapu", 85000, "Logistics")
employee2 = Employee("Honey", "Somarapu", 95000, "Finance")

fulltime_employee1 = FulltimeEmployee("Mani", "Somarapu", 65000, "IT")
fulltime_employee2 = FulltimeEmployee("Nitish", "Somarapu", 50000, "HR")

total_salary_employees = employee1.salary + employee2.salary
average_salary_employees = employee1.average_salary(total_salary_employees)

total_salary_fulltime_employees = fulltime_employee1.salary + fulltime_employee2.salary
average_salary_fulltime_employees = fulltime_employee1.average_salary(total_salary_fulltime_employees)

print("Average Salary for Employees:", average_salary_employees)
print("Average Salary for Fulltime Employees:", average_salary_fulltime_employees)

Average Salary for Employees: 45000.0
Average Salary for Fulltime Employees: 28750.0


In [14]:
import numpy as np
random_vector = np.random.uniform(1, 20, 20)
print("Original Random Vector:\n", random_vector)

Original Random Vector:
 [13.99152603 12.23731993  4.75117876  6.55871617 18.64533101 19.31917355
  3.68814256 13.89411908 17.72515848  7.16987315  1.87784156  7.19660106
 11.00834709  3.79677802 19.24692108 13.81800118 15.74214202  5.72130686
  5.85311931 19.84287571]


In [15]:
reshaped_array = random_vector.reshape(4, 5)
print(reshaped_array)

[[13.99152603 12.23731993  4.75117876  6.55871617 18.64533101]
 [19.31917355  3.68814256 13.89411908 17.72515848  7.16987315]
 [ 1.87784156  7.19660106 11.00834709  3.79677802 19.24692108]
 [13.81800118 15.74214202  5.72130686  5.85311931 19.84287571]]


In [17]:
reshaped_array[np.arange(4), reshaped_array.argmax(axis=1)] = 0
print("Reshaped Array:\n", reshaped_array)

Reshaped Array:
 [[ 0.         12.23731993  4.75117876  6.55871617  0.        ]
 [ 0.          3.68814256 13.89411908  0.          7.16987315]
 [ 1.87784156  7.19660106  0.          3.79677802  0.        ]
 [13.81800118  0.          5.72130686  5.85311931  0.        ]]
